apiVersion: apps/v1
kind: Deployment
metadata:
  name: death-notes-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: death-notes-api
  template:
    metadata:
      labels:
        app: death-notes-api
    spec:
      imagePullSecrets:
        - name: devops101registry-credentials
      containers:
        - name: notes-api
          image: devops101registry.azurecr.io/death-notes-api:v0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: death-notes-api
spec:
  type: LoadBalancer
  selector:
    app: death-notes-api
  ports:
    - protocol: TCP
      port: 80